version: '3'

services:
  backend:
    build:
      context: ./server
    container_name: invoice_backend
    ports:
      - 4041:3001

  frontend:
    build:
      context: ./client
    container_name: invoice_frontend
    ports:
      - 4040:3000