version: '3'

services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  backend:
    build:
      context: ./server
    container_name: invoice_backend
    ports:
      - 3001:3001

  frontend:
    build:
      context: ./client
    container_name: invoice_frontend
    ports:
      - 4040:3000